name: symspell-ex
on:
  push:
    branches:
      - main
jobs:
  Publish:
    runs-on: ubuntu-latest
    services:
        redis:
            image: redis
            # Set health checks to wait until redis has started
            options: >-
                --health-cmd "redis-cli ping"
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
            ports:
                - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: npm run coverall
        env:
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
          COVERALLS_SERVICE_NAME: "GitHub Action"
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - run: npm run build
      # Publish to npm
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
